public enum Type {
    STRING,
    COMMENT,
    RESERVED_KEYWORD,
    OPERATORS_AND_PUNCTUATION,
    IDENTIFIERS,
    INTEGER_NUMBER,
    REAL_NUMBER,
    HEX,
    Boolean,
    SCIENTIFIC_NOTATION,
    WHITESPACE,
    UNDEFINED,
    ESCAPE_CHAR,
    // new ones:
    DOUBLE_ARRAY,
    STRING_ARRAY,
    INT_ARRAY,
}